//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_1461390_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
